/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_tjunet_loctag_jni_CsiCollect */

#ifndef _Included_top_tjunet_loctag_jni_CsiCollect
#define _Included_top_tjunet_loctag_jni_CsiCollect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_tjunet_loctag_jni_CsiCollect
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_top_tjunet_loctag_jni_CsiCollect_open
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     top_tjunet_loctag_jni_CsiCollect
 * Method:    dot11RtLoop
 * Signature: (ILtop/tjunet/loctag/jni/CsiCollect/Type;Ltop/tjunet/loctag/jni/CsiCollect/JNIOnDot11RtReceivedCallback;)I
 */
JNIEXPORT jint JNICALL Java_top_tjunet_loctag_jni_CsiCollect_dot11RtLoop
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     top_tjunet_loctag_jni_CsiCollect
 * Method:    shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_top_tjunet_loctag_jni_CsiCollect_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
