/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_tjunet_loctag_jni_CsiUtils */

#ifndef _Included_top_tjunet_loctag_jni_CsiUtils
#define _Included_top_tjunet_loctag_jni_CsiUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_tjunet_loctag_jni_CsiUtils
 * Method:    buffToDot11Rt
 * Signature: ([BII)Ltop/tjunet/loctag/jni/Dot11Rt;
 */
JNIEXPORT jobject JNICALL Java_top_tjunet_loctag_jni_CsiUtils_buffToDot11Rt
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     top_tjunet_loctag_jni_CsiUtils
 * Method:    buffToCsi4339
 * Signature: ([BII)Ltop/tjunet/loctag/jni/Csi4339;
 */
JNIEXPORT jobject JNICALL Java_top_tjunet_loctag_jni_CsiUtils_buffToCsi4339
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     top_tjunet_loctag_jni_CsiUtils
 * Method:    strToChanspec
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_top_tjunet_loctag_jni_CsiUtils_strToChanspec
  (JNIEnv *, jclass, jstring);

/*
 * Class:     top_tjunet_loctag_jni_CsiUtils
 * Method:    chanspecToStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_tjunet_loctag_jni_CsiUtils_chanspecToStr
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
