/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_tjunet_loctag_jni_CsiCollect_Dot11Rt */

#ifndef _Included_top_tjunet_loctag_jni_CsiCollect_Dot11Rt
#define _Included_top_tjunet_loctag_jni_CsiCollect_Dot11Rt
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
