/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_tjunet_loctag_jni_CsiCollect_JNIOnDot11RtReceivedCallback */

#ifndef _Included_top_tjunet_loctag_jni_CsiCollect_JNIOnDot11RtReceivedCallback
#define _Included_top_tjunet_loctag_jni_CsiCollect_JNIOnDot11RtReceivedCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
