/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_tjunet_loctag_jni_CsiCollect_Type */

#ifndef _Included_top_tjunet_loctag_jni_CsiCollect_Type
#define _Included_top_tjunet_loctag_jni_CsiCollect_Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
