LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := \
	JNIPcap.cpp

LOCAL_MODULE := libJNIPcap

LOCAL_CFLAGS += -DD11AC_IOTYPES -DCHANSPEC_NEW_40MHZ_FORMAT

LOCAL_MODULE_PATH := .

include $(BUILD_SHARED_LIBRARY)

# ndk-build NDK_APPLICATION_MK=Application.mk NDK_APP_OUT=. TARGET_PLATFORM=android-23