/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_tjunet_loctag_ui_capture_CaptureFragment */

#ifndef _Included_top_tjunet_loctag_ui_capture_CaptureFragment
#define _Included_top_tjunet_loctag_ui_capture_CaptureFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_tjunet_loctag_ui_capture_CaptureFragment
 * Method:    ndkDoSometing
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_top_tjunet_loctag_ui_capture_CaptureFragment_ndkDoSometing
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
